[package]
name = "stone-kv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
bincode = "1.3.3"
bytes = "1.1.0"
rand = "0.8.5"
serde = "1.0.139"
serde_derive = "1.0.139"

[features]
