[package]
name = "stone_rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.0"
rmpv = "1.0.0"
tokio = "1.20.0"
tokio-util = { version ="0.7.3", features = ["codec"] }
